"""Seminars and elective courses (credits, workload, prerequisites)."""

from services.mandatory_curriculum_catalog import CurriculumCourseSpec

# Legacy DB course codes → canonical Afeka syllabus codes
LEGACY_ELECTIVE_CODES: dict[int, int] = {
    10200: 10208,  # UI development
}

# Canonical names used in prerequisite strings
PREREQ_NAME_ALIASES: dict[str, str] = {
    "אלגברה ליניארית": "אלגברה ליניארית 1",
    'חדו"א 2': "חשבון דיפרנציאלי ואינטגרלי 2",
    "הסתברות": "מבוא להסתברות",
    "מערכות הפעלה": "מבוא למערכות הפעלה",
    "תקשורת מחשבים": "תקשורת מחשבים לתוכנה",
}

ELECTIVE_CURRICULUM: tuple[CurriculumCourseSpec, ...] = (
    # --- Seminars (2.5 credits) — Afeka syllabus codes ---
    CurriculumCourseSpec(
        11015,
        "סמינר במדעי המחשב",
        2.5,
        category="seminar",
        prereq_and=("תכנון וניתוח אלגוריתמים",),
    ),
    CurriculumCourseSpec(
        10221,
        "סמינר מתקדם בטכנולוגיות סלולריות",
        2.5,
        category="seminar",
        prereq_and=("פיתוח ממשקי משתמש",),
    ),
    CurriculumCourseSpec(
        10352,
        "סמינר בסייבר",
        2.5,
        category="seminar",
        prereq_and=("אבטחת מידע",),
    ),
    CurriculumCourseSpec(
        10355,
        "סמינר בלמידה חישובית",
        2.5,
        category="seminar",
        prereq_and=("תכנון וניתוח אלגוריתמים",),
    ),
    CurriculumCourseSpec(
        10356,
        "סמינר בשפות תכנות",
        2.5,
        category="seminar",
        prereq_and=("עקרונות שפות תכנות",),
    ),
    # --- Helper / prerequisite courses ---
    CurriculumCourseSpec(92101, "למידה חישובית", 3, category="elective"),
    CurriculumCourseSpec(92103, "הסקה סטטיסטית", 3, category="elective"),
    # --- Elective courses ---
    CurriculumCourseSpec(
        92110,
        "סטטיסטיקה",
        3,
        category="elective",
        prereq_and=("מבוא להסתברות",),
    ),
    CurriculumCourseSpec(
        92111,
        "מערכות משובצות מחשב",
        2.5,
        category="elective",
        prereq_and=("מבוא לתכנות מערכות", "ארגון המחשב ושפת סף"),
    ),
    CurriculumCourseSpec(
        10127,
        "בסיסי נתונים",
        3,
        category="elective",
        prereq_and=("מבוא למדעי המחשב",),
    ),
    CurriculumCourseSpec(92113, "כלי פיתוח", 1, category="elective"),
    CurriculumCourseSpec(
        10147,
        "אפיון ממשקי משתמש",
        4,
        category="elective",
        prereq_and=("מבוא למדעי המחשב",),
    ),
    CurriculumCourseSpec(
        92115,
        "עקרונות שפות תכנות",
        4,
        category="elective",
        prerequisites_text="מבוא לתכנות מערכות (במקביל)",
    ),
    CurriculumCourseSpec(
        10313,
        "אבטחת מידע",
        2.5,
        category="elective",
        prereq_and=("אלגברה ליניארית 1", "מבוא להסתברות", "תקשורת מחשבים לתוכנה"),
    ),
    CurriculumCourseSpec(92117, "אתיקה בהנדסת תוכנה", 3, category="elective"),
    CurriculumCourseSpec(
        10206,
        "תורת המידע",
        2.5,
        category="elective",
        prereq_and=("מבוא להסתברות", "אלגברה ליניארית 1"),
    ),
    CurriculumCourseSpec(
        92119,
        "בינה מלאכותית לפיתוח משחקים",
        2.5,
        category="elective",
        prereq_and=("תכנון וניתוח אלגוריתמים", "מבוא לתכנות מערכות"),
    ),
    CurriculumCourseSpec(
        10208,
        "פיתוח ממשקי משתמש",
        4,
        category="elective",
        prereq_and=("תכנות מונחה עצמים", "אפיון ממשקי משתמש"),
    ),
    CurriculumCourseSpec(
        92121,
        "תכנות בפלטפורמת Dot Net",
        4,
        category="elective",
        prereq_and=("תכנות מונחה עצמים",),
    ),
    CurriculumCourseSpec(
        92122,
        "סדנא בתכנות מונחה עצמים עם C++",
        3,
        category="elective",
        prereq_and=("תכנות מונחה עצמים", "מבוא לתכנות מערכות"),
    ),
    CurriculumCourseSpec(
        10219,
        "פיתוח בסביבת IOS",
        2.5,
        category="elective",
        prereq_and=("פיתוח ממשקי משתמש",),
    ),
    CurriculumCourseSpec(
        10220,
        "פיתוח משחקים",
        2.5,
        category="elective",
        prereq_and=("תכנות מונחה עצמים",),
    ),
    CurriculumCourseSpec(
        10224,
        "מבוא לראייה ממוחשבת",
        3,
        category="elective",
        prereq_or_groups=(("למידת מכונה", "למידה חישובית"),),
    ),
    CurriculumCourseSpec(
        10225,
        "עיצוב חזותי של ממשקי משתמש",
        2.5,
        category="elective",
        prereq_and=("פיתוח ממשקי משתמש",),
    ),
    CurriculumCourseSpec(
        10227,
        "אבטחת סייבר",
        2.5,
        category="elective",
        prerequisites_text="אלגברה ליניארית 1, אבטחת מידע (במקביל)",
    ),
    CurriculumCourseSpec(
        10228,
        "אבטחת רשתות תקשורת",
        2.5,
        category="elective",
        aliases=("סייבר-אבטחת רשתות תקשורת",),
        prereq_and=("אבטחת מידע",),
    ),
    CurriculumCourseSpec(
        10233,
        "פיתוח מאובטח",
        2.5,
        category="elective",
        prereq_and=("תכנות מונחה עצמים",),
    ),
    CurriculumCourseSpec(
        10234,
        "אבטחת מובייל",
        2.5,
        category="elective",
        prerequisites_text="פיתוח ממשקי משתמש, אבטחת מידע (במקביל)",
    ),
    CurriculumCourseSpec(
        92132,
        "ניתוח רשתות חברתיות",
        2.5,
        category="elective",
        prereq_and=("מבוא להסתברות",),
    ),
    CurriculumCourseSpec(
        10240,
        "רשתות נוירונים ולמידה עמוקה",
        3,
        category="elective",
        prerequisites_text="מבוא להסתברות, למידת מכונה (במקביל)",
    ),
    CurriculumCourseSpec(
        10243,
        "רשתות נוירונים לראייה ממוחשבת",
        3,
        category="elective",
        prereq_and=("מבוא לראייה ממוחשבת",),
    ),
    CurriculumCourseSpec(
        10245,
        "למידת מכונה",
        3,
        category="elective",
        prereq_and=("מבוא להסתברות", "מבני נתונים"),
    ),
    CurriculumCourseSpec(
        92137,
        "עיבוד שפה טבעית",
        2.5,
        category="elective",
        prerequisites_text="מבוא להסתברות, למידת מכונה (במקביל)",
    ),
    CurriculumCourseSpec(
        10248,
        "קריפטוגרפיה מודרנית",
        2.5,
        category="elective",
        prerequisites_text='מבוא להסתברות, אלגברה ליניארית 1, אבטחת מידע (במקביל)',
    ),
    CurriculumCourseSpec(
        92139,
        "אלגוריתמים אקראיים, מקורבים ומקוונים",
        2.5,
        category="elective",
        prereq_and=("מבוא להסתברות", "אלגוריתמים מתקדמים וסיבוכיות"),
    ),
    CurriculumCourseSpec(
        10266,
        "פיתוח בפלטפורמות WEB",
        3,
        category="elective",
        aliases=("פיתוח בפלטפורמת WEB",),
        prereq_and=("תכנות מונחה עצמים", "פיתוח ממשקי משתמש"),
    ),
    CurriculumCourseSpec(
        92141,
        "סדנה בעיצוב ופיתוח משחקי מחשב",
        2.5,
        category="elective",
        prereq_and=("פיתוח משחקים",),
    ),
    CurriculumCourseSpec(
        92142,
        "גרפיקה ממוחשבת",
        4,
        category="elective",
        prereq_and=("מבוא לתכנות מערכות",),
    ),
    CurriculumCourseSpec(
        92143,
        "מתודולוגיות תכנות Agile",
        2.5,
        category="elective",
        prerequisites_text="מבוא להנדסת תוכנה (במקביל)",
    ),
    CurriculumCourseSpec(
        10351,
        "ניתוח נתוני עתק",
        2.5,
        category="elective",
        prereq_and=("בסיסי נתונים", "מבוא להסתברות"),
    ),
    CurriculumCourseSpec(
        92145,
        "בלוקצ'יין חזון ופרקטיקה",
        2.5,
        category="elective",
        prereq_and=("תכנות מונחה עצמים",),
    ),
    CurriculumCourseSpec(
        92146,
        "אנליזה מתמטית של רשתות",
        2.5,
        category="elective",
        aliases=("אנליזה מתמטית של רשתות חברתיות",),
        prerequisites_text='חשבון דיפרנציאלי ואינטגרלי 2, מבוא להסתברות',
    ),
    CurriculumCourseSpec(
        10359,
        "רכבים אוטונומיים והנדסת אנוש בעולמות ה-AI",
        2.5,
        category="elective",
        prereq_or_groups=(("סטטיסטיקה", "הסקה סטטיסטית"),),
        prereq_and=("תכנות מונחה עצמים",),
    ),
    # --- Additional elective courses ---
    CurriculumCourseSpec(92150, "אבטחת ממשקי משתמש ופרטיות", 3, category="elective",
                         prereq_and=("תכנות מונחה עצמים",)),
    CurriculumCourseSpec(92151, "פיתוח תוכנה מונחה בינה מלאכותית למפתחים", 3, category="elective",
                         prereq_and=("תכנות מונחה עצמים",)),
    # --- Additional seminar ---
    CurriculumCourseSpec(92006, "סמינר בשיטות פיתוח", 2.5, category="seminar",
                         prereq_and=("מבוא להנדסת תוכנה",)),
    # --- elective1 ---
    CurriculumCourseSpec(264011, "מבוא לחקר ביצועים", 3, category="elective1"),
    CurriculumCourseSpec(264012, "מודלים סטוכסטיים", 3, category="elective1",
                         prereq_and=("מבוא להסתברות",)),
    CurriculumCourseSpec(264021, "תורת המשחקים", 3, category="elective1",
                         prereq_and=("מבוא להסתברות",)),
    CurriculumCourseSpec(264022, "כריית מידע", 3, category="elective1",
                         prereq_and=("בסיסי נתונים", "מבוא להסתברות")),
    CurriculumCourseSpec(264023, "שיטות באופטימיזציה וייצור מבוזר", 3, category="elective1"),
)
